name: school_timetable
description: UniTime App.
publish_to: 'none'
version: 4.0.0+28

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations:
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  settings_ui: ^2.0.2
  flutter_essentials_kit: ^2.3.5
  retrofit: ^3.3.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  dropdown_search: ^5.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter_typeahead: ^4.1.1
  glassmorphism: ^3.0.0
  font_awesome_flutter: ^10.3.0
  syncfusion_flutter_calendar: ^20.4.43
  table_calendar: ^3.0.8
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.1
  upgrader: ^6.0.1
  modal_bottom_sheet: ^2.1.2
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  flutter_markdown: ^0.6.13
  url_launcher: ^6.1.8
  flutter_offline: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^9.1.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  retrofit_generator:
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

  assets:
    - assets/images/UniTime.png
    - assets/images/character.png
    - assets/images/notices/noLessons.png
    - assets/images/notices/error.png
    - assets/policy/privacy_policy_en.md
    - assets/policy/privacy_policy_it.md

flutter_icons:
  image_path: "assets/icon.png"
#  image_path_android: "assets/icon.png"
#  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true
  ios: true
  adaptive_icon_background: "#2d3a68"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21